name: build

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make build-rust
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docker:
              - '*.Dockerfile'
      - if: steps.changes.outputs.src == 'true'
        run: cargo make build-docker
