name: build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make build-rust
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make build-docker
